### PR TITLE
new picture

### PR DESCRIPTION
**Pull request by obryniarski**

### CODE REVIEW

**Comment by DavidMChan** [comment]
Please resolve the merge conflicts with master.

**Comment by DavidMChan** [comment]
It doesn't look like you updated the profile picture in the html - aware you sure this is correct? Also, please `git rm` any unused files.

**Comment by obryniarski** [comment]
I'm pretty sure the html is good now and there are no extra jpg files.

**Comment by obryniarski** [comment]
I'm pretty sure it's fine now? I deleted the old pic and added a new one and updated html.

**Pull request merged**
